# Generated by Django 4.2.3 on 2023-08-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
