# Generated by Django 4.2.3 on 2023-08-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
