# Generated by Django 4.2.3 on 2023-08-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_app', '0006_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imageUrl', models.TextField()),
                ('maxFrame', models.IntegerField()),
                ('minFrame', models.IntegerField()),
                ('currentFrame', models.IntegerField()),
                ('step', models.IntegerField()),
                ('url', models.TextField()),
                ('isRocketLaunched', models.BooleanField(null=True)),
                ('message_id', models.IntegerField()),
            ],
        ),
    ]
