# Generated by Django 4.2.3 on 2023-08-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
