# Generated by Django 4.2.3 on 2023-08-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_app', '0010_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.TextField()),
                ('max_frame', models.IntegerField()),
                ('min_frame', models.IntegerField()),
                ('current_frame', models.IntegerField()),
                ('step', models.IntegerField()),
                ('url', models.TextField()),
                ('is_rocket_launched', models.TextField()),
                ('message_id', models.IntegerField()),
                ('max_steps', models.IntegerField()),
            ],
        ),
    ]
